spring:
  application:
    name: IntegrationBus
  config:
    import: "consul:"
  cloud:
    consul:
      host: 91.186.199.152
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
        hostname: localhost
      config:
        enabled: true
        defaultContext: apps
        format: YAML
        watch:
          enabled: true
server:
  port: 8025

keycloak:
  secret: "**********"
  admin_user: "ssoadmin"
  admin_password: "1111"
  admin_realm: "master"