spring:
  application:
    name: IntegrationBus
  config:
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
        hostname: localhost
      config:
        enabled: true
        defaultContext: apps
        format: YAML
        watch:
          enabled: true
server:
  port: 8025

keycloak:
  secret: sQHojGkgdEizTOCXhuNHeL2pnoqj81Gu
#  ssl-required: external