---
  consul_port: "{{ hostvars[groups['deploy_esb_consul'][0]].consul_api_port }}"
  jdbc_string: "jdbc:postgresql://host.docker.internal:5432/postgres"
  jdbc_driver: "org.postgresql.Driver"
  jdbc_dialect: "org.hibernate.dialect.PostgreSQLDialect"
  show_sql: "true"
  base_metrics_path: "/actuator"
  metrics_exposed: "health,prometheus,info,metrics"
  metrics_show_details: "always"
  metrics_show_components: "always"
  sso_host: "keycloak"
  sso_port: "8080"
  sso_realm: "iskr"
  sso_service: "integration-bus"
  log_level: "INFO"
  keycloak_container: "{{ hostvars[groups['deploy_esb_keycloak'][0]].keycloak_container_name }}"
  rabbitmq_host: "{{ hostvars[groups['deploy_esb_rabbit'][0]].ansible_host }}"
  rabbitmq_port: "{{ hostvars[groups['deploy_esb_rabbit'][0]].rabbit_port }}"
  rabbitmq_username: "{{rabbit_admin_user}}"
  rabbitmq_password: "{{rabbit_admin_password}}"
  rabbit_messaging_exchange: "iskr.out_msg"
  rabbit_messaging_queue_email: "iskr.out_msg_mail"
  integration_host: "integration"
  integration_port: "8025"
  smtp_host: "smtp.yandex.ru"
  smtp_port: "465"
  smtp_login: "{{secret_smtp_login}}"
  smtp_token: "{{secret_smtp_password}}"
  smtp_protocol: "smtps"
  smtp_from: "{{smtp_login}}"
  elasticsearch_host: "elasticsearch"
  elasticsearch_port: "9200"
  elasticsearch_timeouts: "30s"
  search_sync_enabled: true
  search_sync_batch: 1000
  search_sync_cron: "\"*/30 * * * * *\""
  
