---
  run_container_image: "openjdk:17-slim"
  pg_user: "{{postgresql_admin_user}}"
  pg_password: "{{postgresql_admin_password}}"
  accounts_consul_default: "apps"
  accounts_consul_host: "host.docker.internal"
  accounts_consul_port: "hostvars[groups['deploy_esb_consul'][0]].consul_api_port"
  discovery_hostname: "host.docker.internal"