---
  consul_port: "{{ hostvars[groups['deploy_esb_consul'][0]].consul_api_port }}"
  jdbc_string: "jdbc:postgresql://host.docker.internal:5432/postgres"
  jdbc_driver: "org.postgresql.Driver"
  jdbc_dialect: "org.hibernate.dialect.PostgreSQLDialect"
  show_sql: "true"
  base_metrics_path: "/actuator"
  metrics_exposed: "health,prometheus,info,metrics"
  metrics_show_details: "always"
  metrics_show_components: "always"
  sso_host: "localhost"
  sso_port: "8080"
  sso_realm: "iskr"
  sso_service: "integration-bus"
  log_level: "INFO"
  keycloak_container: "{{ hostvars[groups['deploy_esb_keycloak'][0]].keycloak_container_name }}"
  rabbitmq_host: "localhost"
  rabbitmq_port: "{{ hostvars[groups['deploy_esb_rabbit'][0]].rabbit_port }}"
  rabbitmq_username: "{{rabbit_admin_user}}"
  rabbitmq_password: "{{rabbit_admin_password}}"
  rabbit_messaging_exchange: "iskr.out_msg"
