---    
  - name: Deploy mailer backend
    hosts: deploy_back_mailer
    tasks: 
      - name: Copy jar file
        synchronize:
          src: "/workspace/artifacts/backend_iskr-mailer.jar"
          dest: "{{base_path}}/docker/apps/"
          mode: push
          use_ssh_args: yes
        delegate_to: localhost

      - name: Give access to socket for install user
        file: 
          path: "/var/run/docker.sock"
          state: file 
          owner: "{{ansible_user}}"
        become: yes

      - name: Stop mailer backend 
        shell: "cd {{base_path}}/docker/ && docker compose -f back_mailer.yml down"
        ignore_errors: yes

      - name: Copy docker build template 
        template: 
          src: "/workspace/templates/backs/build.j2"
          dest: "{{base_path}}/docker/build/Dockerfile-Mailer"

      - name: Copy docker template 
        template: 
          src: "/workspace/templates/backs/mailer.j2"
          dest: "{{base_path}}/docker/back_mailer.yml"

      - name: Build mailer image 
        shell: |
          cd {{base_path}}/docker/ && \
          PG_USER={{pg_user}} \
          PG_PASSWORD={{pg_password}} \
          docker compose -f back_mailer.yml build
      
      - name: Start mailer backend 
        shell: |
          cd {{base_path}}/docker/ && \
          PG_USER={{pg_user}} \
          PG_PASSWORD={{pg_password}} \
          docker compose -f back_mailer.yml up -d