---    
  - name: Deploy books backend
    hosts: deploy_back_books
    tasks: 
      - name: Copy jar file
        synchronize:
          src: "/workspace/artifacts/backend_iskr-books.jar"
          dest: "{{base_path}}/docker/apps/"
          mode: push
          use_ssh_args: yes
        delegate_to: localhost

      - name: Give access to socket for install user
        file: 
          path: "/var/run/docker.sock"
          state: file 
          owner: "{{ansible_user}}"
        become: yes

      - name: Stop books backend 
        shell: "cd {{base_path}}/docker/ && docker compose -f back_books.yml down"
        ignore_errors: yes

      - name: Copy docker build template 
        template: 
          src: "/workspace/templates/backs/build.j2"
          dest: "{{base_path}}/docker/build/Dockerfile-Books"

      - name: Copy docker template 
        template: 
          src: "/workspace/templates/backs/books.j2"
          dest: "{{base_path}}/docker/back_books.yml"

      - name: Build books image 
        shell: |
          cd {{base_path}}/docker/ && \
          PG_USER={{pg_user}} \
          PG_PASSWORD={{pg_password}} \
          docker compose -f back_books.yml build
      
      - name: Start books backend 
        shell: |
          cd {{base_path}}/docker/ && \
          PG_USER={{pg_user}} \
          PG_PASSWORD={{pg_password}} \
          docker compose -f back_books.yml up -d