---    
  - name: Deploy search backend
    hosts: deploy_back_search
    tasks: 
      - name: Copy jar file
        synchronize:
          src: "/workspace/artifacts/backend_iskr-search.jar"
          dest: "{{base_path}}/docker/apps/"
          mode: push
          use_ssh_args: yes
        delegate_to: localhost

      - name: Give access to socket for install user
        file: 
          path: "/var/run/docker.sock"
          state: file 
          owner: "{{ansible_user}}"
        become: yes

      - name: Stop search backend 
        shell: "cd {{base_path}}/docker/ && docker compose -f back_search.yml down"
        ignore_errors: yes

      - name: Copy docker build template 
        template: 
          src: "/workspace/templates/backs/build.j2"
          dest: "{{base_path}}/docker/build/Dockerfile-Search"

      - name: Copy docker template 
        template: 
          src: "/workspace/templates/backs/search.j2"
          dest: "{{base_path}}/docker/back_search.yml"

      - name: Build search image 
        shell: |
          cd {{base_path}}/docker/ && \
          PG_USER={{pg_user}} \
          PG_PASSWORD={{pg_password}} \
          docker compose -f back_search.yml build
      
      - name: Start search backend 
        shell: |
          cd {{base_path}}/docker/ && \
          PG_USER={{pg_user}} \
          PG_PASSWORD={{pg_password}} \
          docker compose -f back_search.yml up -d